stages:
  - test
  - deploy

test:
  image: swamydev/geo-base:latest
  script:
    - make test
  coverage: '/^TOTAL.+?(\d+\%)$/'
  tags:
    - linux

deploy:
  image: python:latest
  needs:
    - job: test
      artifacts: false
  script:
    - make dist
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/groups/10/-/packages/pypi
      dist/*
  tags:
    - linux
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual

